<?php
// $Id: simpletest.module,v 1.4 2004/10/21 19:22:04 weitzman Exp $

function simpletest_help($section) {
  $output = "";

  switch ($section) {
    case 'admin/system/modules#description':
      $output = t("Simple unit testing suite");
      break;
    case 'admin/system/modules/simpletest':
      $output = '';
      break;
  }

  return $output;
}

function simpletest_menu($may_cache) {
  if ($may_cache) {
    $items[] = array('path' => 'admin/simpletest', 'title' => 'simpletest', 'callback' => 'simpletest_admin');
    return $items;
  }
}

function simpletest_admin() {
  if (!defined("SIMPLE_TEST")) {
        define("SIMPLE_TEST", "simpletest/");
    }
    require_once(SIMPLE_TEST . 'unit_tester.php');
    require_once(SIMPLE_TEST . 'web_tester.php');
    require_once(SIMPLE_TEST . 'shell_tester.php');
    require_once(SIMPLE_TEST . 'reporter.php');
    require_once(SIMPLE_TEST . 'mock_objects.php');
    require_once(SIMPLE_TEST . 'extensions/pear_test_case.php');
    require_once(SIMPLE_TEST . 'extensions/phpunit_test_case.php');

    class DrupalUnitTests extends GroupTest {
      function DrupalUnitTests() {
        $this->GroupTest("Drupal unit tests");
        $files = module_invoke_all('simpletest');
        foreach ($files as $file) {
          $this->addTestFile($file);
        }
      }
    }

    if (! defined("TEST_RUNNING")) {
        define("TEST_RUNNING", true);
        $test = &new DrupalUnitTests();
        if (SimpleReporter::inCli()) {
            exit ($test->run(new TextReporter()) ? 0 : 1);
        }
        $test->run(new HtmlReporter());
    }
}

function simpletest_simpletest() {
  return 'modules/simpletest/tests/user_validation_test.php';
}


?>
